version: '3.7'

services:

  portainer:
    image: portainer/portainer:latest
    isolation: process
    ports:
      - 9000:9000
    volumes:
      - "portainer_data:c:/data"
      # named pipes in the *swarm* stack file available in >=19.03
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine
    networks:
      - portainer_net

volumes:
  portainer_data:

networks:
  portainer_net: