version: '3.4'

services:
  whoami:
    image: christianacca/kestrel-whoami:1.0
    labels:
      traefik.enable: 'true'
      traefik.docker.network: traefik_webgateway
      traefik.frontend.rule: 'Host:whoami.docker.localhost'
    networks:
      - public

networks:
  public:
    external:
      name: traefik_webgateway