version: '3.4'

# articles used to construct this compose:
# * [Letting Traefik run on Worker Nodes](https://blog.mikesir87.io/2018/07/letting-traefik-run-on-worker-nodes/)
# * [Secure Traefik dashboard with https and password in docker](https://medium.com/@xavier.priour/secure-traefik-dashboard-with-https-and-password-in-docker-5b657e2aa15f)

services:
  socat:
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - private
  proxy:
    image: traefik
    command: 
      - "--api"
      - "--keepTrailingSlash=true"
      - "--docker"
      - "--docker.exposedByDefault=false"
      - "--docker.endpoint=tcp://socat:2375"
      - "--docker.domain=localhost"
      - "--docker.swarmMode"
    ports:
      - "81:80"
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.backend: traefik
        traefik.docker.network: ${TRAEFIK_STACK}_web
        traefik.frontend.rule: 'Host:traefik.localhost'
        # clear text pwd: Pn7-x6C@4xvP9,g
        traefik.frontend.auth.basic.users: 'docker:$$apr1$$Cv2tp6SH$$hoSgKoXezpBUTSm6A8REP0'
        traefik.port: 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
      - private


networks:
  web:
  private: