version: '3.4'

# articles used to construct this compose:
# * [Letting Traefik run on Worker Nodes](https://blog.mikesir87.io/2018/07/letting-traefik-run-on-worker-nodes/)
# * [Secure Traefik dashboard with https and password in docker](https://medium.com/@xavier.priour/secure-traefik-dashboard-with-https-and-password-in-docker-5b657e2aa15f)

services:
  socat:
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - private
  proxy:
    image: traefik
    command: 
      - "--api"
      - "--defaultEntryPoints=http"
      - "--entrypoints=Name:http Address::80"
      # clear text pwd: Pn7-x6C@4xvP9,g
      - "--entrypoints=Name:traefik Address::8080 Auth.Basic.Users:docker:$$apr1$$Cv2tp6SH$$hoSgKoXezpBUTSm6A8REP0"
      - "--keepTrailingSlash=true"
      - "--ping"
      - "--ping.entrypoint=http"
      - "--docker"
      - "--docker.exposedByDefault=false"
      - "--docker.endpoint=tcp://socat:2375"
      - "--docker.domain=docker.localhost"
      - "--docker.swarmMode"
    ports:
      - "81:80"
      # if you need X-Real-Ip/X-Forwarded-For header to be the client making the request you will need to use host mode publishing
      # see issue: https://github.com/moby/moby/issues/25526
      # EG:
      # - target: 80
      #   published: 81
      #   protocol: tcp
      #   mode: host
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.backend: traefik
        traefik.docker.network: ${TRAEFIK_STACK}_web
        traefik.frontend.rule: 'Host:traefik.docker.localhost'
        traefik.port: 8080
    networks:
      - web
      - private


networks:
  web:
  private: