version: '3.7'

services:
  whoami:
    image: christianacca/kestrel-whoami:1.0.0
    networks:
      - public
    deploy:
      replicas: 2
      labels:
        traefik.enable: 'true'
        traefik.docker.network: ${TRAEFIK_STACK}_web
        traefik.frontend.rule: 'Host:whoami.docker.localhost'
        traefik.port: 80

networks:
  public:
    external: true
    name: ${TRAEFIK_STACK}_web