version: '3.5'

services: 
  httpclient-test:
    image: christianacca/httpclient-test:${TAG:-latest}
    build:
      context: ./src
      dockerfile: Dockerfile
    environment: 
      - HttpRunner__Url=https://httpbin.org/response-headers?freeform=hello
      - HttpRunner__RequestIntervals__0=00:00:05
      - HttpRunner__RequestIntervals__1=
      - HttpRunner__RequestIntervals__2=00:00:03