version: '3.5'

services:
  whoami:
    image: christianacca/kestrel-whoami:1.0
    networks:
      - default
    environment: 
      - Kestrel__Limits__KeepAliveTimeout=00:00:20
    deploy:
      replicas: 2

networks: 
  default:
    driver: overlay
    attachable: true