version: '3.4'

# articles used to construct this compose:
# * [Secure Traefik dashboard with https and password in docker](https://medium.com/@xavier.priour/secure-traefik-dashboard-with-https-and-password-in-docker-5b657e2aa15f)

services:
  proxy:
    image: traefik
    command: 
      - "--api"
      - "--defaultEntryPoints=http"
      - "--entrypoints=Name:http Address::80"
      # clear text pwd: Pn7-x6C@4xvP9,g
      - "--entrypoints=Name:traefik Address::8080 Auth.Basic.Users:docker:$$apr1$$Cv2tp6SH$$hoSgKoXezpBUTSm6A8REP0"
      - "--keepTrailingSlash=true"
      - "--ping"
      - "--ping.entrypoint=http"
      - "--docker"
      - "--docker.exposedByDefault=false"
      - "--docker.domain=docker.localhost"
    ports:
      - "81:80"
    labels:
      traefik.enable: 'true'
      traefik.docker.network: traefik_webgateway
      traefik.frontend.rule: 'Host:traefik.docker.localhost'
      # traefik dashboard port
      traefik.port: 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webgateway

networks:
  webgateway: