version: '3.5'

services: 
  whoami-client:
    image: christianacca/httpclient-request:1.0
    environment: 
      - HttpRunner__Url=http://test-bed_whoami/api/whoami
      - HttpRunner__RequestIntervals__0=00:00:05
      - HttpRunner__RequestIntervals__1=00:00:02
      - HttpRunner__RequestIntervals__2=00:00:25
    networks: 
      - test-bed_default

  monitor:
    image: corfr/tcpdump
    network_mode: "service:whoami-client"
    volumes: 
      - "./dumps:/data"
    command: "-i any tcp -w /data/client.pcapng"
    depends_on:
      - whoami-client

networks:
  test-bed_default:
    external: true