version: '3.7'

services:
  whoami:
    image: containous/whoami
    networks:
      - public
    deploy:
      replicas: 2
      labels:
        traefik.docker.network: ${TRAEFIK_STACK}_web
        traefik.enable: 'true'
        traefik.port: 80
        traefik.backend.loadbalancer.swarm: 'true'

networks:
  public:
    external: true
    name: ${TRAEFIK_STACK}_web