version: '3.7'

services:

  db:
    image: "christianacca/mssql-server-windows-express:${SQL_TAG}"
    environment:
      sa_password: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
      attach_dbs: "[{ 'dbName': 'Octopus', 'dbFiles': ['c:\\\\sql\\\\userdbs\\\\data\\\\Octopus.mdf', 'c:\\\\sql\\\\userdbs\\\\log\\\\Octopus_log.ldf'] }]"
    # isolation: process
    healthcheck:
      test: [ "CMD", "sqlcmd", "-S", "db,1433", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "select 1" ]
      interval: 10s
      retries: 10
      start_period: 30s
    volumes:
      - "db-data:c:/sql/userdbs/data"
      - "db-logs:c:/sql/userdbs/log"
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.platform.os == windows
    networks:
      - octo-net

  server:
    image: octopusdeploy/octopusdeploy${OCTOPUS_SERVER_REPO_SUFFIX}:${OCTOPUS_VERSION}
    environment:
      OctopusAdminUsername: "${OCTOPUS_ADMIN_USERNAME}"
      OctopusAdminPassword: "${OCTOPUS_ADMIN_PASSWORD}"
      sqlDbConnectionString: "Server=db,1433;Initial Catalog=Octopus;Persist Security Info=False;User ID=sa;Password=${SA_PASSWORD};MultipleActiveResultSets=False;Connection Timeout=30;"
      # MasterKey: C80c72OCglaRCTEhBwHMWQ==
    # isolation: process
    ports:
      - "81:81"
    healthcheck:
      test: ["CMD", "powershell", "-file", "./Server/healthcheck-server.ps1"]
      interval: 20s
      timeout: 20s
      retries: 6
      start_period: 120s
    volumes:
      - "server-import:C:/Import"
      - "server-repository:C:/Repository"
      - "server-artifacts:C:/Artifacts"
      - "server-tasklogs:C:/TaskLogs"
      - "server-masterkey:C:/MasterKey"
      - "server-serverlogs:C:/Octopus/Logs"
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.platform.os == windows
    networks:
      - octo-net

  tentacle:
    image: mridev.azurecr.io/octopusdeploy/tentacle${OCTOPUS_TENTACLE_REPO_SUFFIX}:${TENTACLE_VERSION}
    environment:
      ServerUsername: "${OCTOPUS_ADMIN_USERNAME}"
      ServerPassword: "${OCTOPUS_ADMIN_PASSWORD}"
      TargetEnvironment: "Development"
      TargetRole: "app-server"
      TargetName: docker-tentacle
      ServerUrl: "http://server:81"
      PublicHostNameConfiguration: Custom
      CustomPublicHostName: tentacle
    # isolation: process
    stdin_open: true #Process sits and waits for ReadLine
    healthcheck:
      test: ["CMD", "powershell", "-file", "./Tentacle/healthcheck-tentacle.ps1"]
      interval: 20s
      timeout: 20s
      retries: 6
      start_period: 120s
    volumes:
      - "tentacle-applications:C:/Applications"
      - "tentacle-home:C:/TentacleHome"
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.platform.os == windows
    networks:
      - octo-net

volumes:
  db-data:
  db-logs:
  server-import:
  server-repository:
  server-artifacts:
  server-tasklogs:
  server-masterkey:
  server-serverlogs:
  tentacle-applications:
  tentacle-home:
      
networks:
  octo-net:
